[workspace]
members = ["summ-core", "summ-meta"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
summ-core = { path = "summ-core" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
postcard = { version = "1", features = ["alloc"] }
redb = "2"
